Repository WildCodeSchool-2023-09/php-p2-strasbouq, pull requests merged in 2023-11, with the labels that each got.

#8 S2 us11 fix css index
  public/assets/css/index.css
  public/assets/css/personal_bouquet.css
  public/assets/css/style.css
  public/assets/images/bouquet_champetre.jpg
  public/assets/images/bouquet_rond.jpg
  public/assets/images/cosmos.jpg
  public/assets/images/dahlia.jpg
  public/assets/images/eucalyptus.jpg
  public/assets/images/fougere.jpg
  public/assets/images/pivoine.jpg
  public/assets/images/rose.jpg
  public/assets/images/tulipe.jpg
  src/Controller/PersonalBouquetController.php
  src/View/Home/index.html.twig
  src/View/Home/personal_bouquet.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Fix

#4 ajout de la page personal bouquet et des images qui vont avec MAJ a prévoir pour le media query
  public/assets/css/personal_bouquet.css
  public/assets/css/style.css
  public/assets/images/bouquet_champetre.jpg
  public/assets/images/bouquet_rond.jpg
  public/assets/images/cosmos.jpg
  public/assets/images/dahlia.jpg
  public/assets/images/eucalyptus.jpg
  public/assets/images/fougere.jpg
  public/assets/images/pivoine.jpg
  public/assets/images/rose.jpg
  public/assets/images/tulipe.jpg
  src/Controller/PersonalBouquetController.php
  src/View/Home/index.html.twig
  src/View/Home/personal_bouquet.html.twig
  src/routes.php
Labels: help wanted

#6 S2 12 add signup
  public/assets/css/contact.css
  public/assets/css/index.css
  public/assets/css/login.css
  public/assets/css/signup.css
  public/assets/css/style.css
  src/Controller/ContactController.php
  src/Controller/LoginController.php
  src/Controller/UserController.php
  src/View/Home/contact.html.twig
  src/View/Home/login.html.twig
  src/View/Home/signup.html.twig
  src/routes.php
Labels: help wanted

#11 S3 us18 security contact
  database.sql
  public/assets/css/contact.css
  public/assets/css/signup.css
  src/Controller/ContactController.php
  src/Controller/UserController.php
  src/Controller/VerifyController.php
  src/Model/ContactManager.php
  src/Model/UserManager.php
  src/View/Home/contact.html.twig
  src/View/Home/signup.html.twig
  src/routes.php
Labels: bug

#9 S2 us9 10 add navbar footer myaccount 17
  .gitignore
  composer.json
  composer.lock
  database.sql
  public/assets/css/general.css
  public/assets/css/index.css
  public/assets/css/style.css
  public/assets/images/account.png
  public/assets/images/layer2.png
  public/assets/images/panier.png
  public/script.js
  src/View/Integers/footer.html.twig
  src/View/Integers/navbar.html.twig
  src/View/Javascript/script.js
  src/View/layout.html.twig
Labels: enhancement, help wanted
